### ISSUE TITLE
Undefined symbols for architecture x86_64:

### ISSUE THREAD

**Issue by ameenudheen** [MercuryPay/MagTek.iDynamo.ObjC#3]
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_MTSCRA", referenced from:
      objc-class-ref in iDynamoController.o
      objc-class-ref in BLEScannerList.o
      objc-class-ref in audioController.o
      objc-class-ref in MTDataViewerViewController.o

while using Swift sample project

**Comment by agharris73** [comment]
Morning ameenudheen, did you setup the MTSCRA SDK provided by MagTek? https://www.magtek.com/content/documentationfiles/d99875568.pdf

**Comment by ameenudheen** [comment]
Thanks Andrew


Thanks,
Ameenudheen Irshad
Q*Burst | *www.qburst.com

**Comment by agharris73** [comment]
If you have any more questions please let us know.  - Andrew

**Comment by ameenudheen** [comment]
Sure



Thanks,
Ameenudheen Irshad
Q*Burst | *www.qburst.com
